# zenbot backfill gdax.BTC-USD --days=1100
# zenbot backfill gdax.ETH-USD --days=1100
# zenbot backfill gdax.LTC-USD --days=1100
# zenbot backfill gdax.BCH-USD --days=1100
# zenbot backfill gdax.ETC-USD --days=1100
# zenbot backfill gdax.ZRX-USD --days=1100
zenbot backfill gdax.BTC-USD --days=90
zenbot backfill gdax.ETH-USD --days=90
zenbot backfill gdax.LTC-USD --days=90
zenbot backfill gdax.BCH-USD --days=90
zenbot backfill gdax.ETC-USD --days=90
zenbot backfill gdax.ZRX-USD --days=90
